### PR TITLE
Fix some problems with directory creation via Python setup script.

### PR DESCRIPTION
**Pull request by kwertyops**

### CODE REVIEW

**Comment by NeskireDK** [comment]
Thanks for this patch. Yes setup as is is broken due to missing / paths and escapes. 

Tested with PR 18 and this succeeds in installing without warnings at least.

**Comment by kwertyops** [comment]
Also worth mentioning that the curly brace expansion for `mkdir` didn't work as intended (at least on Ubuntu). The shell called by os.system() appears to not support curly brace expansion.

I have another update that just explicitly creates them one by one, or else a hack that calls '/bin/bash -c "mkdir ...."'. Not sure which would be preferred here.

**Review by Luctia — APPROVED** [review]
LGTM

**Comment by Luctia** [comment]
> Also worth mentioning that the curly brace expansion for `mkdir` didn't work as intended (at least on Ubuntu). The shell called by os.system() appears to not support curly brace expansion.
> 
> I have another update that just explicitly creates them one by one, or else a hack that calls '/bin/bash -c "mkdir ...."'. Not sure which would be preferred here.

@kwertyops I'd say forcing the shell to use bash is a good idea. I use fish personally and many people use zsh, so making it use something specific is probably a good idea for reproducability.

**Pull request merged**
