### PR TITLE
Feat sabnzbd

### PR DESCRIPTION
**Pull request by vvdaal**
Note: this also has https://github.com/Luctia/ezarr/pull/28

This addresses https://github.com/Luctia/ezarr/issues/27 and adds sabnzbd

### CODE REVIEW

**Review by Luctia — CHANGES_REQUESTED** [review]
Looks good for the most part except for some small parts. I have only looked through the PR in GitHub so far, so before merging I'll probably try it out as well.

**Comment by vvdaal** [comment]
Fixed :)

**Comment by vvdaal** [comment]
> I think all files look good now, but I run into an issue when trying to run this; upon opening `<my-ip>:8081` I get the following message: `External internet access denied - https://sabnzbd.org/access-denied`. I've added the docker-compose config as it is in this PR, so I'm not sure what went wrong or where I should look to fix it. If this is something that can be fixed automatically, please make sure that that happens. If it needs to be done by hand, I think it would be good if something about this was added in the README.

Updated the README as indeed you have to do some manual steps for getting the access. The link already provides instructions but I also added them to the README.

**Comment by Luctia** [comment]
I'm now getting `Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check`. I looked a bit at that page and it seems I should add my hostname to the hostname whitelist in the config file, but after doing that I get the same error. I suspect it might have something to do with the way Docker networks, how have you set that up?

**Comment by vvdaal** [comment]
I'll try and have a look at this soon, basically I think we have to generate a pre-set config file to get it to work properly.

**Review by Luctia — APPROVED** [review]
Approving this PR now. I will add some comments in the README to explain some stuff, but I suspect many usenet users will already be familiar enough with this software they don't need those comments.

**Pull request merged**
